### ISSUE TITLE
Travis Error: Failed resolving git HEAD (https://github.com/jonschlinkert/micromatch 

### ISSUE THREAD

**Issue by phun-ky** [es128/anymatch#12]
Just got this error in our Travis build from fetching micromatch, a dependency for anymatch (which is required in our build form karma)

    npm ERR! Failed resolving git HEAD (https://github.com/jonschlinkert/micromatch) fatal: ambiguous argument '2.3.0': unknown revision or path not in the working tree.

    npm ERR! Failed resolving git HEAD (https://github.com/jonschlinkert/micromatch) Use '--' to separate paths from revisions, like this:

    npm ERR! Failed resolving git HEAD (https://github.com/jonschlinkert/micromatch) 'git <command> [<revision>...] -- [<file>...]'

    npm ERR! Failed resolving git HEAD (https://github.com/jonschlinkert/micromatch) 

_This issue probably do not belong here, but I put it here for others to be aware of the issue_

Could this be a version mismatch at your end, or is this a result of bad dep version range in a dependency?

Ref: https://github.com/jonschlinkert/micromatch/issues/46

**Comment by es128** [comment]
I can't reproduce. I suspect it was a transient issue in the npm registry around the time that the new version was being published.

**Comment by phun-ky** [comment]
Will come back on this when/if I have more data. For the moment, it is still reproduced

**Comment by phun-ky** [comment]
https://github.com/jonschlinkert/micromatch/issues/46#issuecomment-155205417
