### ISSUE TITLE
Looking for anti-match / not-match ability

### ISSUE THREAD

**Issue by ORESoftware** [es128/anymatch#18]
Re: https://github.com/paulmillr/chokidar/issues/569

I am looking for a way to only match any file in my project that ends with with `.tsx`

however, it looks like chokidar only supports and ignored option.

so should mean that I need to ignore anything that does not match `/\.tsx$/`

can this be achieved with anymatch? Hope the question makes sense, thanks

**Comment by jonschlinkert** [comment]
To negate, you can prefix glob patterns with `!`, e.g. `!**/*.tsx`

**Comment by ORESoftware** [comment]
yeah I saw that and tried that and it didn't work, let me try it again, I think what I had was:

`!**/**.tsx`

I will try yours:

`!**/*.tsx`

**Comment by ORESoftware** [comment]
it doesn't work, sorry, I just tried it :(

**Comment by jonschlinkert** [comment]
yeah, consecutive stars, `**` have the same meaning as `*` when they are _not_ the only thing in a path segment. 

please paste your entire config here so we can debug

**Comment by ORESoftware** [comment]
sure thing, __dirname is just the root of my project

const watcher = chokidar.watch(__dirname, {
    // ignored: /\.[^tsx]$/,
    ignored: '!**/*.tsx',
    // ignored: ['**/.git/**/*', '**/**.js', '**/.idea/**/*'],
    ignoreInitial: true
});

**Comment by ORESoftware** [comment]
as you can see I have tried a few things......

**Comment by jonschlinkert** [comment]
Oh, wait. I misread that, I thought you wanted to ignore all `.tsx` files. You were clear enough, I just misread it. 

Try something like this:

```js
chokidar.watch('**/*.tsx', {ignored: /node_modules/})
  .on('all', (event, path) => {
    console.log(event, path);
  });
```

**Comment by ORESoftware** [comment]
ha of course, that might work, let me try it

**Comment by ORESoftware** [comment]
that seemed to work, kudos to you sir! however just FYI the negation logic with the ! should have worked with chokidar ignored, but it didn't so there seems to be some bug there

**Comment by es128** [comment]
Closing, can continue to discuss at https://github.com/paulmillr/chokidar/issues/569
