### ISSUE TITLE
checking in...

### ISSUE THREAD

**Issue by jonschlinkert** [es128/anymatch#3]
just checking in to make sure you haven't had any problems with micromatch on gulp-watch/chokidar. feel free to close if not

**Comment by es128** [comment]
I actually *just* published anymatch 1.2.0 a couple hours ago, so we'll see [fingers crossed]. If any glob matching issues come up, don't worry, you'll hear about it. :smile_cat:

**Comment by jonschlinkert** [comment]
ah, lol. didn't notice that. I thought it was the other day. 

> don't worry, you'll hear about it.

haha. I'm sure I will

**Comment by jonschlinkert** [comment]
I mean won't! won't...

**Comment by es128** [comment]
emoji are totally failing today with the lack of finger crossing and wood knocking symbols

**Comment by jonschlinkert** [comment]
lol good thing they aren't needed! btw want me to add you to micromatch, in case you need something and I'm not around?

**Comment by es128** [comment]
Sure, can't hurt and I'd be happy to collab on it. 

If you're envisioning an unlikely scenario of needing an emergency fix would need npm publish rights also to effectively mitigate the problem. Doubt it would ever come to that though - "glob-matching emergency" is basically an oxymoron. 

But I could help with triaging issues and that kind of thing.

**Comment by jonschlinkert** [comment]
done! that's exactly the kind of thing I had in mind. I'll add you to npm too

**Comment by jonschlinkert** [comment]
okay, I added you to npm and as a collab for micromatch, [braces](https://github.com/jonschlinkert/braces), and [fill-range](https://github.com/jonschlinkert/fill-range), since those are used by micromatch. thanks!

**Comment by es128** [comment]
:+1:

**Comment by es128** [comment]
You may want to double-check the github side of those other two - doesn't seem like it has kicked in yet -

**Comment by jonschlinkert** [comment]
done. got distracted for minute lol thx

**Comment by sveinatle** [comment]
Hey guys. Seems like after switching to micromatch, chokidar started failing on Windows. The [chokidar CI already caught it](https://ci.appveyor.com/project/es128/chokidar/branch/master/job/rewrg9yq8g2jru45), but I just wanted to notify you in case you are more focused on Linux :)

In my case I noticed the problem after resetting my project which cause the latest anymatch to be used. Any paths that didn't point straight into cwd would never trigger any file events. Or in other words, it would never find any files outside cwd. It doesn't matter if the paths are a combination of opts.cwd or just default opts.cwd.

Forcing chokidar to use anymatch 1.1.0 resolved it for me.

**Comment by jonschlinkert** [comment]
thanks for letting us know. the `cwd` part is something I don't think we looked at today. so that's good to know. 

> but I just wanted to notify you in case you are more focused on Linux :)

https://github.com/jonschlinkert/micromatch/issues/17

today was a windows day. lol

**Comment by sveinatle** [comment]
I just realized you were already on top of it in that thread, so I deleted my comment seconds before you posted your reply here... I know windows can be a pita, so thank you both very much for your hard work on supporting it! It's appreciated :)

**Comment by jonschlinkert** [comment]
ha, no worries. and of course you're very welcome. I appreciate the feedback always.
