### ISSUE TITLE
1.2+ gives install permissions error for docker-compose installation dependencies of micromatch.

### ISSUE THREAD

**Issue by ryanmt** [es128/anymatch#4]
Switching to 1.1 resolves that again.  

All that is required to replicate is running `npm install` on a docker installation with the two versions.  I'm happy to help debug further as necessary.

**Comment by es128** [comment]
Can you isolate which dependencies are causing the issue and attain a greater understanding of why it's happening? Does excluding devDependencies have an impact (`npm install --production`)?

**Comment by es128** [comment]
@ryanmt need more details to be able to try to help with resolving this. Not even sure what you mean by "with the two versions".
