### ISSUE TITLE
negated globs in an array with other positive matchers not respected

### ISSUE THREAD

**Issue by es128** [es128/anymatch#6]
```js
> am(['*.*', '!*.{js,txt}'], 'b.js')
true
```

**Comment by jonschlinkert** [comment]
Have you confirmed whether or not this issue originates in micromatch? If so I'll be back from vacation tomorrow evening and will look into it ASAP

**Comment by es128** [comment]
It definitely doesn't.  It's an anymatch design problem - just never paid attention to it before.

**Comment by jonschlinkert** [comment]
Okay, wanted to make sure.

**Comment by es128** [comment]
Fixed in https://github.com/es128/anymatch/tree/fix-6. Branched from fix-5 branch, so waiting for #7 to be reviewed & merged so that when I open a PR for this one it'll have a clean diff.
