### ISSUE TITLE
Allow micromatch options?

### ISSUE THREAD

**Issue by timkendrick** [es128/anymatch#9]
Great work on anymatch, it's just what I needed!

Is there any chance of being able to pass options to the `micromatch.isMatch()` method, e.g. `{ dot: true }` as seen in the [micromatch API docs](https://github.com/jonschlinkert/micromatch#ismatch)?

**Comment by tunnckoCore** [comment]
it would be cool to see it as 12th element of the function, lol.

**Comment by timkendrick** [comment]
I'm guessing that with this addition, the signature would be:

`anymatch(matchers, testString, [options], [returnIndex], [startIndex], [endIndex])`

Should be fairly trivial to implement, seeing as it's a different type to the other arguments... I agree that it's not the cleanest though.

**Comment by es128** [comment]
@timkendrick yes, as discussed, the challenge here would be what to do with the API signature. It has been my intention so far for anymatch to simply operate with good defaults, but I agree that customizing options should be allowed.

I just have to think on whether I want to break the API and go to 2.0 or do something else.

If there is going to be an `[options]` all the other existing arguments would probably get rolled into it rather than just extending the signature as in your example above.

**Comment by es128** [comment]
Or maybe it would be more like `anymatch(matchers, [options], testString...` in order to be able to use it with a bound matcher function. Wonder if this could be added without a breaking change.

Would be happy to hear any other ideas and perspectives about this.

**Comment by timkendrick** [comment]
Well I imagine 95% of all `anymatch` use cases are just detecting whether there is a match or not using standard defaults, whereas the `returnIndex`, `startIndex` and `endIndex` (and perhaps globbing options too) all seem fairly niche to me, and could be passed as a separate `[options]` object.

If it were up to me, I'd release a `2.0` with a signature like this:

`anymatch(matchers, testString, [options])`

...where you'd have `options.returnIndex`, `options.glob` etc: 

```javascript
var match = anymatch(['*.js', '*.css'], testString, {
  returnIndex: true,
  glob: {
    dot: true
  }
});
```

I personally prefer putting booleans in an `options` argument like this, seeing as otherwise they're confusing to read, unless you know the signature off by heart.

This is all just personal preference though.

**Comment by timkendrick** [comment]
Also, I wasn't entirely sure what the purpose of the `startIndex` and `endIndex` arguments is – couldn't you just do `var boundedMatchers = matchers.slice(startIndex, endIndex)` before running the `anymatch()` test?

**Comment by timkendrick** [comment]
On second thoughts, how about just returning the actual rule that matched (i.e. the string/regexp/function), rather than its index?

That way you get rid of the confusing interplay between `returnIndex` and `startIndex`/`endIndex`, and if you really need the index of the rule you can always do `matchers.indexOf(returnedMatch)`.

...so you could do something like:

```javascript
var matchers = ['*.js', '*.css'];
var testString = 'index.js';

var matchedRule = anymatch(matchers, testString, { returnRule: true });
var matchedIndex = matchers.indexOf(matchedRule);

assert(matchedRule === "*.js");
assert(matchedIndex === 0);
```

I feel like I may be wading in a bit heavily here though, so let me know if I'm missing the bigger picture!

**Comment by timkendrick** [comment]
@es128 - Just seen your comment now about the bound matchers. I get your point about sticking the `options` before the `testString`, to make currying easier. It struck me as a little unusual though, seeing as most npm packages (`minimatch`, `del`, all sorts really) that specify an `[options]` parameter all seem to have it as the last (non-callback) argument, which seems to me to be the de facto convention.

If it were me, I'd follow the `minimatch` signature as closely as possible (seeing as `anymatch` seems to be very popular as a drop-in replacement), and then maybe make a separate module that builds on it to facilitate the flashier-but-presumably-much-less-popular "bound function" use case. Then again, this is all just me speculating, so feel free to ignore.

**Comment by tunnckoCore** [comment]
> If it were up to me, I'd release a 2.0 with a signature like this:

I think we should follow micromatch signature. e.g.
 `anymatch(files, patterns, opts)` not `anymatch(matchers, filepath, opts)`

what about

```js
var matcher = require('is-match')

function isMatchers (fp, matchers, opts) {
  if (typeof fp !== 'string') {
    throw new TypeError('is-matchers expect `fp` be string')
  }
  opts = typeof opts === 'object' ? opts : {}
  matchers = Array.isArray(matchers) ? matchers : [matchers]

  var len = matchers.length
  var i = 0

  while (i < len) {
    var match = matchers[i++]
    var isMatch = matcher(match, opts)
    if (!isMatch(fp)) {
      continue
    }
    return true
  }
  return false
}

var matchers = [
  'path/to/file.js',
  'path/anyjs/**/*.js',
  /foo.js$/,
  function (string) {
    return string.indexOf('bar') !== -1 && string.length > 10
  }
]

console.log(isMatchers('path/to/file.js', matchers)) // true
console.log(isMatchers('path/anyjs/baz.js', matchers)) // true
console.log(isMatchers('path/to/foo.js', matchers)) // true
console.log(isMatchers('path/to/bar.js', matchers)) // true
console.log(isMatchers('bar.js', matchers)) // false
```

**Comment by tunnckoCore** [comment]
Do the job that i think is the purpose of this lib - matching with array of different type of matchers (mixed).

At all currently the lib is too complex and "flexible" and confusing, imo.

**Comment by tunnckoCore** [comment]
also you will be able to pass arrays in that matchers array

```js
var matchers = [
  'path/to/file.js',
  ['path/anyjs/**/*.js', '!path/anyjs/**/foo.js'],
  /foo.js$/,
  ['barbaz', '!barfaz'],
  function (string) {
    return string.indexOf('bar') !== -1 && string.length > 10
  }
]
```

**Comment by tunnckoCore** [comment]
hm, okey, that not work, lol. need tests

**Comment by es128** [comment]
Well thanks for all the opinions folks, but each feature is there for a reason and were added organically in response to actual needs. I utilize them in anysort for instance, which was used to support the desired functionality in Brunch configurations. 

The bound matcher functionality from my perspective is not as niche as you seem to think and is important for performance reasons in some implementations, which corresponds to the purpose behind `startIndex` and `endIndex` as well.

Whatever you may feel about the current API signature, my bias is heavily toward backward compatibility. So I see a choice between two options for accommodating this request.

1. Make `options` an optional argument between `matchers` and `testString` as mentioned above. Concerned about the possibility of this getting too messy to maintain, but in theory it should be simple enough to add in considering the argument types of object and string are very definite. I understand the point about optional arguments in the middle typically only coming before a callback, but there are plenty of examples of overloaded and complex method signatures, even in node core, that make me not consider this a substantial barrier to going with this choice.
2. Introduce an entirely new public method with a signature that is not encumbered by history. That could be like one of the proposals above, except `anymatch.foo(...)` instead of just `anymatch(...)`. Or perhaps something like `anymatch.custom(options)` which returns an equivalent instance of the current `anymatch` function except bound to use the `options` that were passed.

**Comment by tunnckoCore** [comment]
> Make options an optional argument between matchers and testString as mentioned above. 

why not as first place? LOL, it would be the best place.

> but there are plenty of examples of overloaded and complex method signatures, even in node core

that's not means it is encouraging to continue to do it, lol. in same logic - why to use promises when decades use callbacks ("even in node core [modules]")?

Dont think Im aggressive, Im just curios why people love to continue to do the things wrong, not following signatures, semantics and etc, even when they think for new major release and it is considerable to have breaking changes.

**Comment by timkendrick** [comment]
@es128 – thanks for the responses. Sounds like you've got a clear vision for what you want anymatch to do. Go for it!

I was just looking for a drop-in replacement for minimatch that adds regexp and filter function support, so I think I'm probably going to go for multimatch instead (if he accepts my [pull request](https://github.com/sindresorhus/multimatch/pull/13), that is).

Time for me to bow out of this conversation... hope it goes well!

**Comment by es128** [comment]
@timkendrick have you looked at micromatch's `.matcher()` method? It may already provide what you've been looking for.

**Comment by es128** [comment]
There's a bit of context at https://github.com/es128/anymatch/commit/5d862c7f6a260e4da5ce2511e500a186f5fdeced about how/why anymatch is different, but that doesn't seem relevant to your use case. 

I assume `micromatch.matcher()` does accept the options argument, but if not it can probably be added with less fuss than what happened here. 

Closing this issue for now as the need is likely already met (or will be) elsewhere, but the possibility of API changes here will stay in the back of my mind to potentially be applied in the future.

**Comment by timkendrick** [comment]
Thanks for the tip, @es128 – multimatch's `.matcher()` method is kind of what I was looking for, but I don't think it's quite right. I need to be able to specify an array of patterns (each of which could be a glob, RegExp or function), and match an array of filenames against _any of those_ patterns. The `.matcher()` or `.filter()` micromatch methods only seem to allow one pattern, so I imagine you'd have to reduce the patterns array into a combined matcher function, then use that function to filter the filenames array, which all seems a bit messy. Anyway, thanks for the help!

**Comment by es128** [comment]
Alright well if you don't end up getting what you need from either multimatch or micromatch let me know and I may still be able to help you here.

**Comment by timkendrick** [comment]
Thanks @es128!

**Comment by jonschlinkert** [comment]
fwiw, if we use `.matcher` in the main micromatch export, seems like it would have been a lot easier to add this to micromatch than to extend the functionality of multimatch. just my 2c, I may do this anyway
